version: "3.8"

services:
  backend:
    image: soldesk1184/stays-backend:latest
    container_name: stays-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:stays_password@192.168.111.140:5432/stays_db
      JWT_SECRET_KEY: stays-jwt-secret-key
      FRONTEND_URL: http://10.0.2.139
    restart: unless-stopped
